### ISSUE TITLE
Feature request for Windows 2012 r2 vagrant box

### ISSUE THREAD

**Issue by doomnuggets** [ruzickap/packer-templates#7]
I'm currently working on some windows 2012 automation with your base box.
But I'm running into issues with the WinRM connection while installing ADFS and using HTTPS.

Is there any way we could choose from SSL and non-SSL for the WinRM settings
(inside the guest)?
I manually had to execute the following commands before provisioning to accomplish that.

```
winrm set winrm/config/client/auth @{Basic="true"}
winrm set winrm/config/service/auth @{Basic="true"}
winrm set winrm/config/service @{AllowUnencrypted="true"}
```

Furthermore, I'm unable to install a clean version of the windows 2012 R2 box:

```
==> vagrant: A new version of Vagrant is available: 2.0.4!
==> vagrant: To upgrade visit: https://www.vagrantup.com/downloads.html

Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'peru/windows-server-2012-r2-standard-x64-eval' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: 20180429.01
==> default: Loading metadata for box 'peru/windows-server-2012-r2-standard-x64-eval'
    default: URL: https://vagrantcloud.com/peru/windows-server-2012-r2-standard-x64-eval
==> default: Adding box 'peru/windows-server-2012-r2-standard-x64-eval' (v20180429.01) for provider: virtualbox
    default: Downloading: https://vagrantcloud.com/peru/boxes/windows-server-2012-r2-standard-x64-eval/versions/20180429.01/providers/virtualbox.box
==> default: Successfully added box 'peru/windows-server-2012-r2-standard-x64-eval' (v20180429.01) for 'virtualbox'!
==> default: Importing base box 'peru/windows-server-2012-r2-standard-x64-eval'...
==> default: Matching MAC address for NAT networking...
==> default: Checking if box 'peru/windows-server-2012-r2-standard-x64-eval' is up to date...
==> default: Setting the name of the VM: win2012_default_1525101786285_9048
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
==> default: Forwarding ports...
    default: 3389 (guest) => 3389 (host) (adapter 1)
    default: 5986 (guest) => 5986 (host) (adapter 1)
    default: 5985 (guest) => 55985 (host) (adapter 1)
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: WinRM address: 127.0.0.1:5986
    default: WinRM username: Administrator
    default: WinRM execution_time_limit: PT2H
    default: WinRM transport: ssl
#<Thread:0x00007f8dfa216670@/opt/vagrant/embedded/gems/gems/logging-2.2.2/lib/logging/diagnostic_context.rb:471 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
	21: from /opt/vagrant/embedded/gems/gems/logging-2.2.2/lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'
	20: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.3/lib/vagrant/action/builtin/wait_for_communicator.rb:16:in `block in call'
	19: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.3/plugins/communicators/winrm/communicator.rb:31:in `wait_for_ready'
	18: from /usr/lib/ruby/2.5.0/timeout.rb:108:in `timeout'
	17: from /usr/lib/ruby/2.5.0/timeout.rb:33:in `catch'
	16: from /usr/lib/ruby/2.5.0/timeout.rb:33:in `catch'
	15: from /usr/lib/ruby/2.5.0/timeout.rb:33:in `block in catch'
	14: from /usr/lib/ruby/2.5.0/timeout.rb:93:in `block in timeout'
	13: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.3/plugins/communicators/winrm/communicator.rb:57:in `block in wait_for_ready'
	12: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.3/plugins/communicators/winrm/communicator.rb:106:in `ready?'
	11: from /usr/lib/ruby/2.5.0/timeout.rb:108:in `timeout'
	10: from /usr/lib/ruby/2.5.0/timeout.rb:33:in `catch'
	 9: from /usr/lib/ruby/2.5.0/timeout.rb:33:in `catch'
	 8: from /usr/lib/ruby/2.5.0/timeout.rb:33:in `block in catch'
	 7: from /usr/lib/ruby/2.5.0/timeout.rb:93:in `block in timeout'
	 6: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.3/plugins/communicators/winrm/communicator.rb:107:in `block in ready?'
	 5: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.3/plugins/communicators/winrm/shell.rb:66:in `cmd'
	 4: from /opt/vagrant/embedded/gems/gems/winrm-2.2.3/lib/winrm/connection.rb:44:in `shell'
	 3: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.3/plugins/communicators/winrm/shell.rb:67:in `block in cmd'
	 2: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.3/plugins/communicators/winrm/shell.rb:111:in `execute_with_rescue'
	 1: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.3/plugins/communicators/winrm/shell.rb:114:in `rescue in execute_with_rescue'
/opt/vagrant/embedded/gems/gems/vagrant-2.0.3/plugins/communicators/winrm/shell.rb:152:in `raise_winrm_exception': An SSL error occurred while connecting to WinRM. This usually (VagrantPlugins::CommunicatorWinRM::Errors::SSLError)
occurs when you are using a self-signed certificate and have
not set the WinRM `ssl_peer_verification` config setting to false.

Message: SSL_connect SYSCALL returned=5 errno=0 state=SSLv3/TLS write client hello
#<Thread:0x000055bc978b89a0@/opt/vagrant/embedded/gems/gems/vagrant-2.0.3/lib/vagrant/batch_action.rb:71 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
	21: from /opt/vagrant/embedded/gems/gems/logging-2.2.2/lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'
	20: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.3/lib/vagrant/action/builtin/wait_for_communicator.rb:16:in `block in call'
	19: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.3/plugins/communicators/winrm/communicator.rb:31:in `wait_for_ready'
	18: from /usr/lib/ruby/2.5.0/timeout.rb:108:in `timeout'
	17: from /usr/lib/ruby/2.5.0/timeout.rb:33:in `catch'
	16: from /usr/lib/ruby/2.5.0/timeout.rb:33:in `catch'
	15: from /usr/lib/ruby/2.5.0/timeout.rb:33:in `block in catch'
	14: from /usr/lib/ruby/2.5.0/timeout.rb:93:in `block in timeout'
	13: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.3/plugins/communicators/winrm/communicator.rb:57:in `block in wait_for_ready'
	12: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.3/plugins/communicators/winrm/communicator.rb:106:in `ready?'
	11: from /usr/lib/ruby/2.5.0/timeout.rb:108:in `timeout'
	10: from /usr/lib/ruby/2.5.0/timeout.rb:33:in `catch'
	 9: from /usr/lib/ruby/2.5.0/timeout.rb:33:in `catch'
	 8: from /usr/lib/ruby/2.5.0/timeout.rb:33:in `block in catch'
	 7: from /usr/lib/ruby/2.5.0/timeout.rb:93:in `block in timeout'
	 6: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.3/plugins/communicators/winrm/communicator.rb:107:in `block in ready?'
	 5: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.3/plugins/communicators/winrm/shell.rb:66:in `cmd'
	 4: from /opt/vagrant/embedded/gems/gems/winrm-2.2.3/lib/winrm/connection.rb:44:in `shell'
	 3: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.3/plugins/communicators/winrm/shell.rb:67:in `block in cmd'
	 2: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.3/plugins/communicators/winrm/shell.rb:111:in `execute_with_rescue'
	 1: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.3/plugins/communicators/winrm/shell.rb:114:in `rescue in execute_with_rescue'
/opt/vagrant/embedded/gems/gems/vagrant-2.0.3/plugins/communicators/winrm/shell.rb:152:in `raise_winrm_exception': An SSL error occurred while connecting to WinRM. This usually (VagrantPlugins::CommunicatorWinRM::Errors::SSLError)
occurs when you are using a self-signed certificate and have
not set the WinRM `ssl_peer_verification` config setting to false.

Message: SSL_connect SYSCALL returned=5 errno=0 state=SSLv3/TLS write client hello
An SSL error occurred while connecting to WinRM. This usually
occurs when you are using a self-signed certificate and have
not set the WinRM `ssl_peer_verification` config setting to false.

Message: SSL_connect SYSCALL returned=5 errno=0 state=SSLv3/TLS write client hello
```

**Comment by ruzickap** [comment]
Hello.

I tried these steps to run Win2012 box and it was working for me:

```
pruzicka@peru:/var/tmp/windows-server-2012-r2-standard-x64-eval$ VAGRANT_DEFAULT_PROVIDER=virtualbox vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Checking if box 'peru/windows-server-2012-r2-standard-x64-eval' is up to date...
==> default: Setting the name of the VM: my_vm
==> default: Clearing any previously set forwarded ports...
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
==> default: Forwarding ports...
    default: 3389 (guest) => 3389 (host) (adapter 1)
    default: 5986 (guest) => 5986 (host) (adapter 1)
    default: 5985 (guest) => 55985 (host) (adapter 1)
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: WinRM address: 127.0.0.1:5986
    default: WinRM username: Administrator
    default: WinRM execution_time_limit: PT2H
    default: WinRM transport: ssl
==> default: Machine booted and ready!
==> default: Checking for guest additions in VM...
pruzicka@peru:/var/tmp/windows-server-2012-r2-standard-x64-eval$
```

Can you please check your version of the vagrant plugins + vagrant + virtualbox + box image:

```
$ vagrant plugin list
vagrant-hostmanager (1.8.8)
  - Version Constraint: > 0
vagrant-ignition (0.0.3)
  - Version Constraint: > 0
vagrant-libvirt (0.0.43)
  - Version Constraint: > 0
vagrant-share (1.1.9)
  - Version Constraint: > 0
vagrant-winrm (0.7.0)
  - Version Constraint: > 0

$ vagrant --version
Vagrant 2.0.4

$ rpm -qa | grep ^VirtualBox-5
VirtualBox-5.2.10-1.fc27.x86_64

$ vagrant box list | grep windows-server-2012-r2-standard-x64-eval
peru/windows-server-2012-r2-standard-x64-eval (virtualbox, 20180429.01)
```

I'm using the following script to install WinRM SSL:

https://raw.githubusercontent.com/ansible/ansible/devel/examples/scripts/ConfigureRemotingForAnsible.ps1

It's taken from "autounattend" windows installation:

https://github.com/ruzickap/packer-templates/blob/e6413cc596dd8e7801683e6c671ff00b70463c98/http/windows-2012/Autounattend.xml#L162

I'm pretty sure WinRM can be installed/used without SSL. 
I believe guys managing these repositories may use non-ssl winrm (or using different way of it's initial installation): 

https://github.com/StefanScherer/packer-windows
https://github.com/boxcutter/windows
https://github.com/joefitzgerald/packer-windows

I do not have plans to remove/change WinRM SSL, because I'm only using the script above to configure WinRM - that's the recommended way by Ansible project.

**Comment by doomnuggets** [comment]
You're absolutely correct on the recreation of the bug I'm experiencing.
Sorry for wasting your time here, I think the issues I'm experiencing are very specific to my use case and thus do not apply to the actual base image.

I'll check out the resources you've provided and will try to work around my issue :)

Thanks for your time.
